#!/bin/bash
set -e

SCRIPT_DIR="${BASE_DIR}/scripts/analysis"
cmd="$1"
shift || true

if [[ "$cmd" != "" && -x "${SCRIPT_DIR}/$cmd" ]]; then
    exec "${SCRIPT_DIR}/$cmd" "$@"
else
    echo "Available scripts:"
    cd "$SCRIPT_DIR"
    for i in *; do
        if [[ -x "$i" && ! -d "$i" ]] ; then
            echo "  $i"
        fi
    done
    exit 1
fi
