package refit.scheduler;


public enum REFITSchedulerTaskType {
	NETWORK_ENDPOINT,
	CLIENT_NETWORK_ENDPOINT_WORKER,
	REPLICA_NETWORK_ENDPOINT_WORKER,
	SIGNATURE_STAGE,

	CLIENT_STAGE,
	ORDER_STAGE,
	CHECKPOINT_STAGE,
	UPDATE_STAGE,
	EXECUTION_STAGE,
	COUPLING_STAGE,
	EXEC_COUPLING_STAGE,
	CHANNEL_SENDER_STAGE,
	CHANNEL_RECEIVER_STAGE,

	CLIENT_LIBRARY,
	CLIENT_ENDPOINT_WORKER,
	CLIENT_TASK,
}
